version: "3.8"

services:
  server:
    build:
      context: ./random-movement-server
      dockerfile: Dockerfile
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      retries: 5
      start_period: 30s
    networks:
      - disease_network
    ports:
      - "8080:8080"
  
  analytics:
    build:
      context: ./data-analytics-server
      dockerfile: Dockerfile
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/health"]
      interval: 30s
      retries: 5
      start_period: 30s
    networks:
      - disease_network
    ports:
      - "8081:8081"
  
  gui:
    build:
      context: ./gui
      dockerfile: Dockerfile
    depends_on:
      server:
        condition: service_healthy
      analytics:
        condition: service_healthy
    networks:
      - disease_network
    ports:
      - "5173:5173"

networks:
  disease_network:
