version: "3.8"

services:
  server:
    build:
      context: ./random-movement-server
      dockerfile: Dockerfile
    networks:
      - disease_network
    ports:
      - "8080:8080"
  gui:
    build:
      context: ./gui
      dockerfile: Dockerfile
    depends_on:
      - server
    networks:
      - disease_network
    ports:
      - "5173:5173"

networks:
  disease_network: